#!/usr/bin/env python
import os
import sys
import glob as glob
import numpy as np
import cPickle as cpkl
import optparse

usage = """
%prog SETUP_GET_EXPECTED_NSDS.PKL\n
SETUP_GET_EXPECTED_NSDS.PKL --- setup file ( generated by script_setup_get_expected_NSDs.py )
"""

parser = optparse.OptionParser( usage = usage )

parser.add_option( '--do_psd' , action='store_true' , help='Get theoretical PSDs' )

parser.add_option( '--do_csd' , action='store_true' , help='Get theoretical CSDs' )

( options , args ) = parser.parse_args()

if len( args ) < 1 :
    parser.error( 'You must specify at least SETUP_GET_EXPECTED_NSDs.PKL!' )
    
file = open( args[ 0 ] , 'rb' ) ; setup = cpkl.load( file ) ; file.close()

workdir = os.getcwd() + '/'




if options.do_psd :
    print 'Getting the theoretical PSDs...'
    if 'x_get_expected_noise_PSD.py' not in glob.glob( 'x_get_expected_noise_PSD.py' ) :
        os.system( 'cp %s .' % ( setup['execdir'] + 'x_get_expected_noise_PSD.py' ) )

    psddir = workdir + 'psd/'
    os.system( './x_get_expected_noise_PSD.py --tditype %s --tdigen %s --whichtdi %s --f0 %f --df %f --Nf %d %s'
               % ( setup['tditype'] , setup['tdigen'] , setup['whichtdi'] , setup['f0'] , setup['df'] , setup['Nf'] , psddir ) )

    print 'done'


if options.do_csd :
    print 'Getting the theoretical CSDs...'
    if 'x_get_expected_noise_CSD.py' not in glob.glob( 'x_get_expected_noise_CSD.py' ) :
        os.system( 'cp %s .' % ( setup['execdir'] + 'x_get_expected_noise_CSD.py' ) )

    csddir = workdir + 'csd/'
    os.system( './x_get_expected_noise_CSD.py --tditype %s --tdigen %s --whichtdi %s --f0 %f --df %f --Nf %d %s'
               % ( setup['tditype'] , setup['tdigen'] , setup['whichtdi'] , setup['f0'] , setup['df'] , setup['Nf'] , csddir ) )

    print 'done'




